### ISSUE TITLE
关于掉线问题

### ISSUE THREAD

**Issue by feizhenzhuang** [lyq1996/supplicant#1]
你好，很高兴终于能在github上找到你关于安朗小蝴蝶破解的一些工作，目前 我在研究如何用路由器实现小蝴蝶认证，首先我把aecium这个开源的认证程序编译到openwrt里面去，但是我遇到一个很致命的问题：认证成功几分钟后就会掉线（不知道你遇到过这个问题没）。在网上多方寻找也没有看到解决方法，请问，我能就相关问题和您讨论一下吗？ 感激不尽，最近这个问题搞得我心力交瘁。十分感谢:-D
 我的联系方式：
 qq ：1091960841 
 email： feizhenzhuang@gmail.com

**Comment by feizhenzhuang** [comment]
经测试，你的python端supplicant 是不能认证，而且显示的mac地址与我有线网卡mac地址不同.
 版本： 0.1
安朗版本：3.8.2
 平台： win   
 python：2.7.12
修改过程：我只修改第17行代码 改为我校认证服务器，其余均无修改。
运行python文件：系统弹出dos框 显示mac 地址  ip   host   除mac地址外 其余均显示正确，但是过几分钟dos框自动关闭。我尝试联网均失败，而且 在我用官方小蝴蝶客户端认证成功后，再运行你提供的python文件会导致下线，（我觉得应该是py文件下线申请成功）
![log](https://cloud.githubusercontent.com/assets/13115887/17830821/2dc78df6-670a-11e6-8df5-87b8ea0ea8c2.png)

**Comment by lyq1996** [comment]
已经加你啦，你抓一下包给我看看吧，我修改一下应该可以运行～
