### ISSUE TITLE
OpenWrt

### ISSUE THREAD

**Issue by Yuenggpong** [lyq1996/supplicant#2]
在已经刷好OpenWrt的路由器上如和刷入你的ph文件呢？用了putty好像没反应！求救！

**Comment by Yuenggpong** [comment]
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 2.3M      2.3M         0 100% /rom
tmpfs                    14.4M    156.0K     14.2M   1% /tmp
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock3          384.0K    216.0K    168.0K  56% /overlay
mini_fo:/overlay          2.3M      2.3M         0 100% /
不知道我这个能不能刷入你的Python呢？

**Comment by Yuenggpong** [comment]
root@OpenWrt:~# df -h
Filesystem                Size      Used       Available Use% Mounted on
/dev/root                 2.3M      2.3M         0            100%       /rom
tmpfs                      14.4M    156.0K      14.2M          1%     /tmp
tmpfs                       512.0K      0           512.0K         0%      /dev
/dev/mtdblock3      384.0K   216.0K     168.0K         56%   /overlay
mini_fo:/overlay       2.3M      2.3M         0              100% /

**Comment by lyq1996** [comment]
你这个好像空间过小… python light也要7
8m左右的空间，可以试试桥接吧，端口插wan口，lan口插电脑上，然后电脑填路由器mac地址和ip，理论上认证成功之后整个无线路由器子网都能上网了
